[package]
name = "rust_jissen"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "hello"
path = "src/hello/main.rs"

[[bin]]
name = "rpn"
path = "src/rpn/main.rs"
